# Generated by Django 3.2.6 on 2021-10-11 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 8, 39, 672686), verbose_name='Registratsiya sanasi:'),
        ),
    ]
