# Generated by Django 3.2.6 on 2021-10-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 10, 21, 923976), verbose_name='Registratsiya sanasi:'),
        ),
    ]
