# Generated by Django 3.2.6 on 2021-10-13 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20211013_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 13, 6, 53, 17329), verbose_name='Registratsiya sanasi:'),
        ),
    ]
