# Generated by Django 3.2.6 on 2021-10-13 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 13, 19, 35, 57316), verbose_name='Registratsiya sanasi:'),
        ),
    ]
