# Generated by Django 3.2.6 on 2021-10-13 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_lessons_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkasmodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='linkasmodel',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.lessons'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 13, 21, 15, 793253), verbose_name='Registratsiya sanasi:'),
        ),
    ]
