# Generated by Django 3.2.6 on 2021-10-13 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20211013_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 22, 11, 51, 957461), verbose_name='Registratsiya sanasi:'),
        ),
    ]
