# Generated by Django 3.2.6 on 2021-10-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkasmodel',
            options={'verbose_name': 'Havola', 'verbose_name_plural': "Havolalar ro'yxati"},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 16, 46, 58, 24558), verbose_name='Registratsiya sanasi:'),
        ),
        migrations.RemoveField(
            model_name='teachersmodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='teachersmodel',
            name='skill',
            field=models.ManyToManyField(to='academy.Skill_names'),
        ),
    ]
