# Generated by Django 3.2.6 on 2021-10-17 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20211017_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.skill_names'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 54, 57, 721206), verbose_name='Registratsiya sanasi:'),
        ),
    ]
